artifact_uri: Model selection/1/832efefbc735432c8cfa86093e60f16b/artifacts
end_time: 1620631473282
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 832efefbc735432c8cfa86093e60f16b
run_uuid: 832efefbc735432c8cfa86093e60f16b
source_name: ''
source_type: 4
source_version: ''
start_time: 1620631471137
status: 3
tags: []
user_id: mgerh
