artifact_uri: Model selection/1/dd310dec22fa43f7becec94012b1e58c/artifacts
end_time: 1620595614980
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: dd310dec22fa43f7becec94012b1e58c
run_uuid: dd310dec22fa43f7becec94012b1e58c
source_name: ''
source_type: 4
source_version: ''
start_time: 1620595605093
status: 4
tags: []
user_id: mgerh
