artifact_uri: Model selection/1/5c571c2ab0074be7aabe172395e4324c/artifacts
end_time: 1620595768776
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 5c571c2ab0074be7aabe172395e4324c
run_uuid: 5c571c2ab0074be7aabe172395e4324c
source_name: ''
source_type: 4
source_version: ''
start_time: 1620595763599
status: 3
tags: []
user_id: mgerh
