artifact_uri: Model selection/1/98bc78e0943346dcb491b231cdaf37fc/artifacts
end_time: 1620595837792
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 98bc78e0943346dcb491b231cdaf37fc
run_uuid: 98bc78e0943346dcb491b231cdaf37fc
source_name: ''
source_type: 4
source_version: ''
start_time: 1620595831931
status: 3
tags: []
user_id: mgerh
