artifact_uri: Model selection/1/bfbb6b0531aa4d28bcc08cfa3b306aa3/artifacts
end_time: 1620595680033
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: bfbb6b0531aa4d28bcc08cfa3b306aa3
run_uuid: bfbb6b0531aa4d28bcc08cfa3b306aa3
source_name: ''
source_type: 4
source_version: ''
start_time: 1620595675888
status: 3
tags: []
user_id: mgerh
